### ISSUE TITLE
Is this for real?

### ISSUE THREAD

**Issue by ArjixWasTaken** [Kord-Extensions/template#19]
> Note: This template includes a .editorconfig file that defaults to using tabs for indentation in almost all file types. This is because tabs are more accessible for the blind, or those with impaired vision. We won't accept feedback or PRs targeting this approach.

I am just curious, don't blind people (or people with any sort of physical disability) have assistive software installed on their computers/phones?

Isn't that assistive software ignoring whitespace?
If it is not ignoring whitespace, shouldn't that be your focus instead?

I fail to see how a tab is more accessible.

---

PS: If we are talking about a programmer and not just a code-reviewer, they can use `Ctrl+ArrowRight` or `Ctrl+ArrowLeft` to jump over the group of spaces.

**Comment by ArjixWasTaken** [comment]
Disclaimer: I am not criticising your choice of tabs over spaces, I am just curious on why you think that way.

**Comment by ArjixWasTaken** [comment]
Or another way to interpret this, is that you mean a tab is "wider" than 4 spaces, which would make it easier to see for people that are not fully blind.

But even then, you could just set the space-width to 8 or smth.

Tabs are not guaranteed to be wide, it is not a universal thing.

**Comment by gdude2002** [comment]
Hey, thanks for your curiosity.

It came up in my Internet travels a few years ago that this can be an issue - while it's true that assistive technologies *exist*, it's also true that we are bad (as a society) at building software that accounts for them. I'm unsure if the status quo has changed, but I ran into several visually impaired programmers that - at least back then - talked about how this approach can help them, or people like them.

Tabs have other advantages, variable display width is one, as you've mentioned. However, it's worth remembering that both indentation methods act the same in a good editor from a functionality standpoint, so I think it's a pretty fair concession to make when it especially doesn't really have any major drawback for sighted people.

It's also worth noticing that we (as a society) continue to produce inaccessible software, so I doubt we'll ever end up switching to spaces. There isn't really a reason to anyway either way though, in my opinion.

**Comment by ArjixWasTaken** [comment]
Nice points!

I do agree that tabs vs spaces is usually a non-existent problem for sighted people (when using a good editor).
It mostly is an issue with python, but this is kotlin :)

The only times I notice the existence of tabs, is when I see a git diff with all the tabs replaced by spaces or vice versa, totally not noticeable otherwise!

I'd love to learn the difficulties and workarounds less-sighted people have when programming!
